# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJkDx21bkuYAJMxcb4vUoCh0NyPaKT3w
"""

import pandas as pd

# Dummy data (dictionary)
data = {
    "Country": ["Indonesia", "Iran", "Irak", "Thailand", "Vietnam",
                "Philippines", "Japan", "South Korea", "Australia", "New Zealand"],
    "Capital": ["Jakarta", "Teheran", "Baghdad", "Bangkok", "Hanoi",
                "Manila", "Tokyo", "Seoul", "Canberra", "Wellington"],
    "Population_Millions": [123, 456, 789, 101, 102, 103, 104, 521, 272, 555]
}

df = pd.DataFrame(data)

print(df)

df.to_csv("countries.csv", index=False)

print("\nFile 'countries.csv' berhasil disave")