# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJkDx21bkuYAJMxcb4vUoCh0NyPaKT3w
"""





from google.colab import files

uploaded = files.upload()

print("Country Data:")
print(df)


mean_population = df["Population_Millions"].mean()
std_population = df["Population_Millions"].std()

print("\nStatistics:")
print(f"Mean (Average) Population: {mean_population:.2f} million")
print(f"Standard Deviation: {std_population:.2f} million")