# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJkDx21bkuYAJMxcb4vUoCh0NyPaKT3w
"""

def write_biodata():
    name = input("Enter your name: ")
    age = input("Enter your age: ")
    address = input("Enter your address: ")
    email = input("Enter your email: ")

    with open("Biodata.txt", "w") as file:
        file.write(f"Name    : {name}\n")
        file.write(f"Age     : {age}\n")
        file.write(f"Address : {address}\n")
        file.write(f"Email   : {email}\n")

    print("\nBiodata has been saved successfully.\n")

def read_biodata():
    with open("Biodata.txt", "r") as file:
        print("=== Biodata ===")
        print(file.read())


write_biodata()
read_biodata()